### PR TITLE
partial support for aiohttp 3 and driver session closing

### PR DESCRIPTION
**Pull request by Fahreeve**
@CaptFrozenberg pls add full support for aiohttp 3

### CODE REVIEW

**Comment by CaptFrozenberg** [comment]
There are several points:
- aio.testing seems to be abandoned, pytest with plugin for asyncio looks like a better option (installation of aio.testing gives me an error)
- aiosocks is incompatible with aiohttp 3 and [PR](https://github.com/aio-libs/aiohttp/pull/2539)  from its author to aiohttp is abandoned, also there is an [issue](https://github.com/nibrag/aiosocks/issues/28) in aiosocks itself. So an alternative is [aiosocksy](https://github.com/romis2012/aiosocksy)

**Comment by Fahreeve** [comment]
Ok, lets migrate to pytest and aiosocksy

**Comment by Fahreeve** [comment]
I will rewrite unit tests using pytests

**Comment by CaptFrozenberg** [comment]
Allright, I'll look into replacing aiosocks with aiosocksy

**Comment by Fahreeve** [comment]
don't forget to update https://github.com/Fahreeve/aiovk#features

**Comment by Fahreeve** [comment]
@typeetfunc

**Pull request merged**
